using System.Collections.Generic;
using UnityEngine;
using System;
using System.Collections;

public enum AHAdSdk : int
{
    Adcolony = 5,
    Adfalcon = 6,
    AdGeneraition = 38,
    Admob = 1,
    Admost = 7,
    Aequus = 8,
    Applovin = 9,
    Appodeal = 39,
    Amazon = 40,
    Automattic = 70,
    BidMachine = 41,
    BigoAds = 72,
    BeachFront = 73,
    BeeSwax = 74,
    Colossus = 75,
    Chartboost = 10,
    ChocolatePlatform = 42,
    Conversant = 76,
    Criteo = 43,
    CrossPromotion = 11,
    Csj = 90,
    DataBlocks = 77,
    Xmediator = 44,
    Emodo = 78,
    Emx = 45,
    Equativ = 46,
    Facebook = 4,
    Fluct = 47,
    Flurry = 12,
    Fyber = 13,
    Gam = 2,
    Gravite = 92,
    GroundTruth = 79,
    Hyprmx = 14,
    Imobile = 15,
    ImproveDigital = 48,
    Inmobi = 16,
    Index = 49,
    Ironsource = 17,
    Leadbolt = 18,
    LevelPlay = 93,
    LgUAd = 50,
    Line = 51,
    Maio = 19,
    Max = 20,
    MediaGrid = 80,
    MediaNet = 52,
    Meson = 36,
    Mintegral = 37,
    Mobfox = 21,
    Mobilefuse = 53,
    Moloco = 89,
    Mytarget = 22,
    Nend = 23,
    Nimbus = 69,
    Onetag = 54,
    OpenWrapDfp = 88,
    Openx = 55,
    Ogury = 56,
    Pangle = 24,
    Pubmatic = 57,
    PubNative = 81,
    Prebid = 68,
    Reklamup = 91,
    Rhythmon = 82,
    Rubicon = 58,
    Sharethrough = 59,
    SilverMob = 83,
    Smaato = 25,
    Sonobi = 60,
    Scalemonk = 26,
    Snap = 27,
    Tapdaq = 28,
    Tapjoy = 29,
    Tappx = 84,
    Tencent = 30,
    TripleLift = 61,
    UnderTone = 85,
    Unity = 31,
    Unrulyx = 62,
    Verizon = 32,
    Verve = 63,
    Vpon = 33,
    Vrtcal = 86,
    Vungle = 34,
    Yahoo = 64,
    Yandex = 65,
    Yieldmo = 66,
    Yieldone = 67,
    Zucks = 35,
    Xandr = 87,
    Custom = 998,
    None = 999
}

public enum AHAdFormat : int
{
    Banner = 1,
    Interstitial = 2,
    Native = 3,
    Rewarded = 4,
    RewardedInterstitial = 5,
    SplashScreen = 6
}

public enum AHAdStateResult : int
{
    Unknown = 0,
    Verified = 1,
    Blocked = 2,
    Reported = 3
}

// TODO: Convert it from String to ENUM
public enum AHAdBlockReason : int
{
    BlocklistTypeSecurity = 1,
    BlocklistTypeBrandSafetyVideoOnDisplay = 2,
    BlocklistTypeBrandSafetyPopup = 3,
    BlocklistTypeBrandSafetyAdLpOffensive = 4,
    BlocklistTypeBrandSafetyVideoAutoSound = 5,
    BlocklistTypeBrandSafetyLpBackButtonHijack = 6,
    BlocklistTypeBrandSafetyBrowserLocking = 7,
    BlocklistTypeBrandSafetyPageAutoScroll = 8,
    BlocklistTypeBrandSafetyMobileVibrateLp = 9,
    BlocklistTypeBrandSafetyJsAlertOnEntry = 10,
    BlocklistTypeBrandSafetyUserDefinedDomain = 11,
    BlocklistTypeBrandSafetyAdLpExtremeOffensive = 12,
    BlocklistTypeBrandSafetyLpCategoryAlcohol = 14, // backend jump
    BlocklistTypeBrandSafetyLpCategoryGambling = 15,
    BlocklistTypeBrandSafetyLpCategoryHealth = 16,
    BlocklistTypeBrandSafetyLpCategoryIllegalDrugs = 17,
    BlocklistTypeBrandSafetyLpCategoryLaw = 18,
    BlocklistTypeBrandSafetyLpCategoryMarijuana = 19,
    BlocklistTypeBrandSafetyLpCategoryNews = 20,
    BlocklistTypeBrandSafetyLpCategoryPharmaceuticals = 21,
    BlocklistTypeBrandSafetyLpCategoryReligion = 22,
    BlocklistTypeBrandSafetyLpCategoryTobacco = 23,
    BlocklistTypeBrandSafetyLpCategoryWeightLoss = 24,
    BlocklistTypeBrandSafetyAdLpKeyword = 25,
    BlocklistTypeBrandSafetyLpCategoryCryptocurrency = 26,
    BlocklistTypeBrandSafetyLpCategoryFashionAndBeauty = 27,
    BlocklistTypeBrandSafetyLpCategoryElection = 28,
    BlocklistTypeBrandSafetyUserDefinedApp = 31, // backend jump
    BlocklistTypeBrandSafetyAnimatedGif = 32,
    BlocklistTypeBrandSafetyLpCategorySwimwearAndIntimateApparel = 34,
    BlocklistTypeBrandSafetyLpCategoryWeapons = 35,
    BlocklistTypeBrandSafetyFileDownload = 36,
    BlocklistTypeBrandSafetyInvalidTraffic = 37,
    BlocklistTypeBrandSafetyAppStoreCategoryBooks = 100,
    BlocklistTypeBrandSafetyAppStoreCategoryBusiness = 101,
    BlocklistTypeBrandSafetyAppStoreCategoryDeveloperTools = 102,
    BlocklistTypeBrandSafetyAppStoreCategoryEducation = 103,
    BlocklistTypeBrandSafetyAppStoreCategoryEntertainment = 104,
    BlocklistTypeBrandSafetyAppStoreCategoryFinance = 105,
    BlocklistTypeBrandSafetyAppStoreCategoryFoodDrink = 106,
    BlocklistTypeBrandSafetyAppStoreCategoryGames = 107,
    BlocklistTypeBrandSafetyAppStoreCategoryGraphicsDesign = 108,
    BlocklistTypeBrandSafetyAppStoreCategoryHealthFitness = 109,
    BlocklistTypeBrandSafetyAppStoreCategoryLifestyle = 110,
    BlocklistTypeBrandSafetyAppStoreCategoryKids = 111,
    BlocklistTypeBrandSafetyAppStoreCategoryMagazinesNewspapers = 112,
    BlocklistTypeBrandSafetyAppStoreCategoryMedical = 113,
    BlocklistTypeBrandSafetyAppStoreCategoryMusic = 114,
    BlocklistTypeBrandSafetyAppStoreCategoryNavigation = 115,
    BlocklistTypeBrandSafetyAppStoreCategoryNews = 116,
    BlocklistTypeBrandSafetyAppStoreCategoryPhotoVideo = 117,
    BlocklistTypeBrandSafetyAppStoreCategoryProductivity = 118,
    BlocklistTypeBrandSafetyAppStoreCategoryReference = 119,
    BlocklistTypeBrandSafetyAppStoreCategorySafariExtensions = 120,
    BlocklistTypeBrandSafetyAppStoreCategoryShopping = 121,
    BlocklistTypeBrandSafetyAppStoreCategorySocialNetworking = 122,
    BlocklistTypeBrandSafetyAppStoreCategorySports = 123,
    BlocklistTypeBrandSafetyAppStoreCategoryTravel = 124,
    BlocklistTypeBrandSafetyAppStoreCategoryUtilities = 125,
    BlocklistTypeBrandSafetyAppStoreCategoryWeather = 126,
    BlocklistTypeBrandSafetyAppStoreCategoryStickers = 127,
    BlocklistTypeBrandSafetyPlayStoreCategoryArtDesign = 200,
    BlocklistTypeBrandSafetyPlayStoreCategoryAutoVehicles = 201,
    BlocklistTypeBrandSafetyPlayStoreCategoryBeauty = 202,
    BlocklistTypeBrandSafetyPlayStoreCategoryBooksReference = 203,
    BlocklistTypeBrandSafetyPlayStoreCategoryBusiness = 204,
    BlocklistTypeBrandSafetyPlayStoreCategoryComics = 205,
    BlocklistTypeBrandSafetyPlayStoreCategoryCommunication = 206,
    BlocklistTypeBrandSafetyPlayStoreCategoryDating = 207,
    BlocklistTypeBrandSafetyPlayStoreCategoryEducation = 208,
    BlocklistTypeBrandSafetyPlayStoreCategoryEntertainment = 209,
    BlocklistTypeBrandSafetyPlayStoreCategoryEvents = 210,
    BlocklistTypeBrandSafetyPlayStoreCategoryFinance = 211,
    BlocklistTypeBrandSafetyPlayStoreCategoryFoodDrink = 212,
    BlocklistTypeBrandSafetyPlayStoreCategoryHealthFitness = 213,
    BlocklistTypeBrandSafetyPlayStoreCategoryHouseHome = 214,
    BlocklistTypeBrandSafetyPlayStoreCategoryLibrariesDemo = 215,
    BlocklistTypeBrandSafetyPlayStoreCategoryLifestyle = 216,
    BlocklistTypeBrandSafetyPlayStoreCategoryMapsNavigation = 217,
    BlocklistTypeBrandSafetyPlayStoreCategoryMedical = 218,
    BlocklistTypeBrandSafetyPlayStoreCategoryMusicAudio = 219,
    BlocklistTypeBrandSafetyPlayStoreCategoryNewsMagazines = 220,
    BlocklistTypeBrandSafetyPlayStoreCategoryParenting = 221,
    BlocklistTypeBrandSafetyPlayStoreCategoryPersonalization = 222,
    BlocklistTypeBrandSafetyPlayStoreCategoryPhotography = 223,
    BlocklistTypeBrandSafetyPlayStoreCategoryProductivity = 224,
    BlocklistTypeBrandSafetyPlayStoreCategoryShopping = 225,
    BlocklistTypeBrandSafetyPlayStoreCategorySocial = 226,
    BlocklistTypeBrandSafetyPlayStoreCategorySports = 227,
    BlocklistTypeBrandSafetyPlayStoreCategoryTools = 228,
    BlocklistTypeBrandSafetyPlayStoreCategoryTravelLocal = 229,
    BlocklistTypeBrandSafetyPlayStoreCategoryVideoPlayersEditors = 230,
    BlocklistTypeBrandSafetyPlayStoreCategoryWeather = 231,
    BlocklistTypeBrandSafetyPlayStoreCategoryGamesAction = 232,
    BlocklistTypeBrandSafetyPlayStoreCategoryGamesAdventure = 233,
    BlocklistTypeBrandSafetyPlayStoreCategoryGamesArcade = 234,
    BlocklistTypeBrandSafetyPlayStoreCategoryGamesBoard = 235,
    BlocklistTypeBrandSafetyPlayStoreCategoryGamesCard = 236,
    BlocklistTypeBrandSafetyPlayStoreCategoryGamesCasino = 237,
    BlocklistTypeBrandSafetyPlayStoreCategoryGamesCasual = 238,
    BlocklistTypeBrandSafetyPlayStoreCategoryGamesEducational = 239,
    BlocklistTypeBrandSafetyPlayStoreCategoryGamesMusic = 240,
    BlocklistTypeBrandSafetyPlayStoreCategoryGamesPuzzle = 241,
    BlocklistTypeBrandSafetyPlayStoreCategoryGamesRacing = 242,
    BlocklistTypeBrandSafetyPlayStoreCategoryGamesRolePlaying = 243,
    BlocklistTypeBrandSafetyPlayStoreCategoryGamesSimulation = 244,
    BlocklistTypeBrandSafetyPlayStoreCategoryGamesSports = 245,
    BlocklistTypeBrandSafetyPlayStoreCategoryGamesStrategy = 246,
    BlocklistTypeBrandSafetyPlayStoreCategoryGamesTrivia = 247,
    BlocklistTypeBrandSafetyPlayStoreCategoryGamesWord = 248,
    BlocklistTypeBrandSafetyMarkedByTheUser = 515,
    AppExperienceForceCloseAd = 901,
    None = 9998,
    Unknown = 9999
}

public enum AHAdAnalyzedResult : int
{
    AnalyzedSuccessfullyOnAdLoad = 0,
    WillAnalyzeOnDisplay = 1,
    NotAnalyzedUnableToFetchAdapter = 2,
    NotAnalyzedAdNetworkAdapterNotSupported = 3,
    NotAnalyzedUnsupportedContent = 4,
    NotAnalyzedHouseCampaign = 5,
    NotAnalyzedDueToTargetedAdNetworks = 6,
    NotAnalyzedUnsupportedAdNetworkVersion = 7,
    NoResultAnalyzed = 999
}
